name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: 🔖 Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Install Zip
        run: sudo apt-get install zip
      - name: Convert library to Arduino IDE compatible format
        run: |
          mkdir -p Mhz19/src
          mkdir -p Mhz19/examples/HardwareSerial
          mkdir -p Mhz19/examples/SoftwareSerial
          cp LICENSE Mhz19
          cp library.properties Mhz19
          cp include/Mhz19.h Mhz19/src
          cp src/Mhz19.cc Mhz19/src
          cp examples/HardwareSerial/*.ino Mhz19/examples/HardwareSerial
          cp examples/SoftwareSerial/*.ino Mhz19/examples/SoftwareSerial
          zip -r Mhz19.zip Mhz19/*
      - name: Add release asset Mhz19.zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: Mhz19.zip
          asset_path: ./Mhz19.zip
          asset_content_type: application/zip
